---
# handlers file for sonar
handlers:
  - name: daemon-reload
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: restart sonarqube
    ansible.builtin.systemd:
      name: sonarqube
      state: restarted
