---
# tasks file for common
- name: apt update
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: common package installation
  ansible.builtin.apt:
    state: present
    update_cache: yes
    name: "{{ common_package }}"